stages:
  - test
  - merge
  - deploy

before_script:
  - whoami
  - hostname
  - pwd

test_fixfeat:
  stage: test
  script:
    - echo "Test handled inside docker"
  only:
    - fixfeat

merge_to_testing:
  stage: merge
  script:
    - git fetch origin
    - git checkout testing
    - git pull origin testing
    - git merge origin/fixfeat --no-ff -m "CI: merge fixfeat into testing"
    - git push origin testing
  only:
    - fixfeat

deploy_testing:
  stage: deploy
  script:
    - cd /home/diyorossi/docker-laravel-crud/app/laravel-crud-ajax
    - docker compose down
    - docker compose up -d --build
  only:
    - fixfeat
