stages:
  - test
  - merge
  - deploy

before_script:
  - whoami
  - pwd

# =========================
# TEST STAGE
# =========================
test_fixfeat:
  stage: test
  script: |
    echo "Skip test for now"
  only:
    - fixfeat

# =========================
# MERGE STAGE
# =========================
merge_to_testing:
  stage: merge
  script: |
    git config --global user.email "ci@gitlab.com"
    git config --global user.name "GitLab CI"

    git fetch origin
    git checkout testing
    git pull origin testing
    git merge "$CI_COMMIT_SHA" --no-ff -m "CI: merge fixfeat into testing"
    git push origin testing
  only:
    - fixfeat
    
# =========================
# DEPLOY STAGE (TESTING)
# =========================
deploy_testing:
  stage: deploy
  only:
    - fixfeat
  needs:
    - merge_to_testing
  script: |
    ssh -o StrictHostKeyChecking=no -p 2223 root@172.17.92.192 << 'EOF'
      set -e
      cd /laravel-crud-ajax
      git pull origin testing
    EOF
